### PR TITLE
Bump action's versions

### LINKED ISSUE #369: kubectl apply -f doesn't work
Hi,
I'm trying to install the reflector without success on my k8s cluster (v1.27.4).
When I use the following command:

_kubectl -n kube-system apply -f  https://github.com/emberstack/kubernetes-reflector/releases/latest/download/reflector.yaml_

I'll get:
_the namespace from the provided object "default" does not match the namespace "kube-system". You must pass '--namespace=default' to perform this operation._

I can install only in the default namespace, but It doesn't work when I deploy my secret with the following annotation:
     reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
     reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "dev-1,dev-2,dev-[0-9]*"

### PR DESCRIPTION
**Pull request by bonddim**
- Enable dependabot for actions
- Bump action's versions to latest

Fixes #369

### CODE REVIEW

**Comment by bonddim** [comment]
Waiting for new release of `azure/setup-helm` action 
https://github.com/Azure/setup-helm/pull/121

**Review by winromulus — APPROVED** [review]
LGTM

**Comment by bonddim** [comment]
Removed `azure/setup-helm` action. As it does not required. Helm is pre-installed on GitHub-hosted runners https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#package-management

**Review by winromulus — APPROVED** [review]
LGTM

**Pull request merged**
