### PR TITLE
Reflector fix

### PR DESCRIPTION
**Pull request by shcherbak**
https://github.com/emberstack/kubernetes-reflector/issues/372

i am trying to fix selfsigned ssl error, but dotnet ignores linux /etc/ssl/certs trusted storage

please, help to run reflector on baremetal cluster with custom selfsigned CA

### CODE REVIEW

**Comment by winromulus** [comment]
This is very custom and environment specific. Please re-work this as "additionalInitContainers" and "additionalVolumes" and "additionalVolumeMounts" so everyone can customize their deployment. In your case the helm generated volumes are specific to your need.

**Review by winromulus — CHANGES_REQUESTED** [review]
To be refactored for extensibility (see PR comments)

**Comment by shcherbak** [comment]
@winromulus adding root-ca to trusted certificates not helps to resolve ssl connection error. Can you help to customize kuberentes csharp client to set skip-ssl-verify?

```
           - name: Kestrel__Certificates__Default__Path
              value: "/etc/ssl/certs/rootCACert.pem"
            - name: ES_Kestrel__Certificates__Default__Path
              value: "/etc/ssl/certs/rootCACert.pem"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: "/etc/ssl/certs/rootCACert.pem"
```
is there any environment variables to overide dotnet trusted certifcates storage ?

**Comment by shcherbak** [comment]
closing because release 7.0.199 resolved the issue

**Pull request closed without merging**
