### PR TITLE
feat(helm): cronjob mode, be able to override the healthcheck

### PR DESCRIPTION
**Pull request by idrissneumann**
Issue #emberstack/kubernetes-reflector/issues/292

### CODE REVIEW

**Comment by aeimer** [comment]
@idrissneumann what is the purpose of this change? How will it fix #292 ?

**Comment by idrissneumann** [comment]
@aeimer The default healthcheck is not sufficient. httpGet on `healthz` always answer `healthy` even when it's down.

We're working on finding another one and we'll be able to complete with this feature on the helmchart.

**Comment by aeimer** [comment]
Ok why then the MR? It will not fix anything. I guess you should first implement a full fix.

Dont understand me wrong, I would appreciate a fix very much. But I dont see any improvement in that change. You can also adapt the helm chart locally.

**Comment by idrissneumann** [comment]
@aeimer We're still working on this matter because we're getting the same issue. Once we'll find a sufficient healthcheck, we'll maybe complete this pr with another healthcheck in the default values.yaml (or give it in a comment in the issue).

In anycase it remains better to be able to override and add healthcheck that aren't hardcoded in the templates.

**Comment by aeimer** [comment]
I dont understand the point of this MR then. Is there magical healthendpoint appear somewhere? I dont get it.

Sadly this repo seems to be not that supported anymore, so no clue if we could merge it anyways...

**Comment by idrissneumann** [comment]
@aeimer In our side we observe that the ps is still running inside the container (we wanted to add a healthcheck on a `ps` result command, that's why we started this pr).

Reflector stop working after around 2 days, so I guess until we get a real healthcheck, we'll just transform the deployment into a cronjob with a limited duration (we also can add a healthcheck on the `uptime` command).

**Comment by aeimer** [comment]
I see, makes sense. But that temporary fix would be nice to have for all people, wouldnt it?

**Comment by idrissneumann** [comment]
@aeimer I updated this pr with a cronjob mode, this way the reflector pod will be restarted every 15min (scheduling overridable) and the time to live of the pod 10min. It should do the trick as a workaround until the code is properly fixed.

Pretty easy to enable, just a flag like that:

```yaml
cron:
  enable: true
```

The the deployment is replaced by a cronjob :)

**Comment by aeimer** [comment]
@idrissneumann what creative workaround. The pod will be stopped with the `activeDeadlineSeconds`? I mean yeah why not. But I guess that this repo is dead anyways. So we cant merge this...

**Comment by idrissneumann** [comment]
> The pod will be stopped with the activeDeadlineSeconds ?

Yes exactly, it will live during 10 minutes and be relaunched every 15 minutes (we can override those settings)

> But I guess that this repo is dead anyways. So we cant merge this...

I got the same feeling, thats why we also pushed the helmchart to our internal helm registry.

That's why our fork got another protected branch with [this github action](https://github.com/shippeo/kubernetes-reflector/blob/shippeo/.github/workflows/helm-deliver.yaml) that perform the delivery. This way we're able to maintain this chart until we find the time to replace it using kyverno or something else.

From my perspective, I vouch for Kyverno, I think it got a more strong community.

**Comment by idrissneumann** [comment]
By the way, someone post this alternative in your issue. Seems pretty promising too: https://github.com/ktsstudio/mirrors

I'll give it a try :)

**Review by winromulus — APPROVED** [review]
LGTM

**Pull request merged**
